In [8]:
import numpy as np
import scipy

In [45]:
from itertools import combinations, product

def number_of_patterns(matrix: np.ndarray) -> int:
    n_rows, n_cols = matrix.shape
    patterns_count = 0
    # print(np.linalg.det(matrix))

    for subset_size in range(2, n_cols + 1):
        for columns in combinations(range(n_cols), subset_size):
            for binary_string in product([0, 1], repeat=subset_size):
                submatrix = matrix[:, columns]

                if not any((submatrix == np.array(binary_string)).all(axis=1)):
                    is_minimal = True
                    for subsubset_size in range(1, subset_size):
                        for subcolumns in combinations(columns, subsubset_size):
                            subsubmatrix = matrix[:, subcolumns]
                            subbinary_string = tuple(binary_string[i] for i, col in enumerate(columns) if col in subcolumns)
                            if not any((subsubmatrix == np.array(subbinary_string)).all(axis=1)):
                                is_minimal = False
                                break
                        if not is_minimal:
                            break
                    if is_minimal:
                        print("столбцы =", *tuple(col + 1 for col in columns)," значения =", *binary_string)
                        patterns_count += 1

    return patterns_count

# matrix = np.array([
#     [1, 0, 0, 0, 0],
#     [0, 1, 0, 0, 0],
#     [0, 0, 1, 0, 0],
#     [0, 0, 0, 1, 0],
#     [0, 0, 0, 0, 1]
# ])

# matrix = np.array([
#     [0, 1, 1, 0],
#     [1, 1, 1, 1],
#     [0, 0, 0, 1]
# ])

matrix = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 1]
])

# matrix = np.array([
#     [1, 1],
#     [1, 1],
# ])

num = number_of_patterns(matrix)
print(num)


столбцы = 1 2  значения = 1 1
столбцы = 1 3  значения = 1 1
столбцы = 2 3  значения = 1 1
столбцы = 1 2 3  значения = 0 0 0
4


In [11]:
import numpy as np
import itertools

def is_unique(matrix, unique_matrices):
    for unique_matrix in unique_matrices:
        for perm_rows in itertools.permutations(unique_matrix):
            perm_matrix = np.array(perm_rows)
            for permuted_matrix in itertools.permutations(perm_matrix.T):
                permuted_matrix = np.array(permuted_matrix).T
                if np.array_equal(matrix, permuted_matrix) or np.array_equal(matrix, 1 - permuted_matrix):
                    return False
                # Проверяем все возможные инверсии столбцов
                for col_inversion in itertools.product([0, 1], repeat=matrix.shape[1]):
                    inverted_matrix = permuted_matrix.copy()
                    for col_idx, invert in enumerate(col_inversion):
                        if invert == 1:
                            inverted_matrix[:, col_idx] = 1 - inverted_matrix[:, col_idx]
                    if np.array_equal(matrix, inverted_matrix):
                        return False
    return True

def generate_unique_matrices(m, n):
    binary_strings = list(itertools.product([0, 1], repeat=m*n))
    unique_matrices = []

    for binary_string in binary_strings:
        matrix = np.array(binary_string).reshape(m, n)
        if is_unique(matrix, unique_matrices):
            unique_matrices.append(matrix)

  return unique_matrices

m = 4
n = 4
unique_matrices = generate_unique_matrices(m, n)

d = {}
for idx, matrix in enumerate(unique_matrices):
  nums = number_of_patterns(matrix)
  if nums not in d:
    d[nums] = 1
  else:
    d[nums] += 1
  print(f"Matrix {idx + 1}:\n{matrix}")
  print(f"Зависимости: {nums}\n")
print(dict(sorted(d.items())))
print(idx + 1)


KeyboardInterrupt: 

In [76]:
def get_subsets(elements):
        subsets = [[]]
        for element in elements:
            new_subsets = [subset + [element] for subset in subsets]
            subsets.extend(new_subsets)
        filtered_subsets = [subset for subset in subsets if 2 <= len(subset) <= len(subsets) - 1]
        return filtered_subsets

def del_col(matrix: np.ndarray) -> list:
    num_rows, num_cols = matrix.shape
    columns = []

    for col_idx in range(num_cols):
        if np.any(matrix[:, col_idx] != matrix[0, col_idx]):
            columns.append(col_idx)

    return matrix[:, columns]

def del_row(matrix: np.ndarray) -> list:
    unique_rows = np.unique(matrix, axis=0)
    return unique_rows

def to_identity(matrix: np.ndarray, n:int) -> int:
    if n == 2:
      for j in range(n):
        if np.sum(matrix[:, j]) != 1:
          return False

    else:
      for j in range(n):
          if np.sum(matrix[:, j]) == n - 1:
              matrix[:, j] = 1 - matrix[:, j]

      for i in range(n):
          if np.sum(matrix[i, :]) != 1:
              return False

    return True

def pattern_in_matrix(matrix: np.ndarray) -> int:
  ans = 0
  matrix = del_col(del_row(matrix))
  m, n = np.shape(matrix)
  if m == 1:
    return 0
  if n == 1:
    return 0
  if m == n:
    if to_identity(matrix, n):
      print('d')
      ans = n * (n - 1) / 2 + 1
    else:
      ans = 0
  if m < n:
    ans = 0
  return int(ans)

def number_of_patterns(matrix: np.ndarray) -> int:
  ans = 0
  m, n = np.shape(matrix)
  column_combinations = get_subsets(list(range(0, n)))
  print(column_combinations)
  for j in column_combinations:
    ans += pattern_in_matrix(matrix[:, j])
    print(matrix[:, j])
    print(pattern_in_matrix(matrix[:, j]))
  return ans


# matrix = np.array([[0, 1, 1, 1],
#                    [0, 1, 1, 1],
#                    [0, 1, 0, 0],
#                    [0, 1, 0, 0],
#                    [0, 1, 1, 0]])

matrix = np.array([[0, 0, 0, 0],
                   [0, 1, 1, 1]])


print(number_of_patterns(matrix))

[[0, 1], [0, 2], [1, 2], [0, 1, 2], [0, 3], [1, 3], [0, 1, 3], [2, 3], [0, 2, 3], [1, 2, 3], [0, 1, 2, 3]]
[[0 0]
 [0 1]]
0
[[0 0]
 [0 1]]
0
d
[[0 0]
 [1 1]]
d
2
d
[[0 0 0]
 [0 1 1]]
d
2
[[0 0]
 [0 1]]
0
d
[[0 0]
 [1 1]]
d
2
d
[[0 0 0]
 [0 1 1]]
d
2
d
[[0 0]
 [1 1]]
d
2
d
[[0 0 0]
 [0 1 1]]
d
2
[[0 0 0]
 [1 1 1]]
0
[[0 0 0 0]
 [0 1 1 1]]
0
12


In [24]:
def get_subsets(elements):
        subsets = [[]]
        for element in elements:
            new_subsets = [subset + [element] for subset in subsets]
            subsets.extend(new_subsets)
        filtered_subsets = [subset for subset in subsets if 2 <= len(subset) <= len(subsets) - 1]
        return filtered_subsets


False
